blank_issues_enabled: false
contact_links:
  - name: Contact Support
    url: https://naninovel.com/support
    about: We're not providing support via GitHub issues; see naninovel.com/support for more info.
