blank_issues_enabled: false
contact_links:
  - name: Naninovel Support
    url: https://naninovel.com/support
    about: We're not providing support via GitHub issues. Please see the link above for available options.
